version: '3.8'

services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - text-analyzer-api

  text-analyzer-api:
    build: ./text-analyzer-api
    environment:
      - PORT=3000
      - MONGODB_URI=mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongo:27017/${MONGO_DB}?authSource=admin
      - REDIS_URL=redis://:${REDIS_PASSWORD}@redis:6379
      - KEYCLOAK_URL=http://keycloak:8080
      - KEYCLOAK_REALM=${KEYCLOAK_REALM}
      - KEYCLOAK_CLIENT_ID=${KEYCLOAK_CLIENT_ID}
    volumes:
      - keycloak_secrets:/tmp/keycloak_secrets:ro
    depends_on:
      - mongo
      - redis
      - keycloak-initializer
    command: sh -c "export KEYCLOAK_CLIENT_SECRET=$$(cat /tmp/keycloak_secrets/keycloak_secrets | grep KEYCLOAK_CLIENT_SECRET | cut -d '=' -f2) && npm start"

  mongo:
    image: mongo:4.4
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:6-alpine
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis-data:/data

volumes:
  mongo-data:
  redis-data: