services:
  nginx:
    container_name: api-gateway-nginx
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./:/etc/nginx/
      - ./logs:/var/log/nginx
    restart: unless-stopped

  text-analyzer-api:
    build: ./text-analyzer-api
    environment:
      - PORT=3000
      - MONGODB_URI=mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongo:27017/${MONGO_DB}?authSource=admin
      - REDIS_URL=redis://:${REDIS_PASSWORD}@redis:6379

    depends_on:
      - mongo
      - redis
    command: sh -c "npm start"

  mongo:
    image: mongo:4.4
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:latest
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis-data:/data

volumes:
  mongo-data:
  redis-data: